name: $(Date:yyyyMMdd)$(rev:.r)

variables:
- group: LB00225_common_vars_TEST

trigger: none
#  batch: true
#  branches:
#    include:
#      - develop
#  paths:
#    exclude:
#      - devops/*

resources:
  repositories:
  - repository: CommonTemplates
    type: git
    endpoint: common-template-service-connection
    name: GestioneCicloDiVitaSw/CommonTemplatesYaml
    ref: 'refs/heads/develop'

stages: 
- template: build-stages/library/dotnet-build-stages.yaml@CommonTemplates
  parameters:
    commonVariableGroup: LB00225_common_vars_TEST_NO_FAKE
    enableDebug: true
    linuxPoolName: linuxpoolcontainersvil
    nugetConfigFile: Passi.Authentication.Cookie/nuget.config
    withDotnetPush: false
    withDotnetPack: false
    #dotnetPackbuildProperties: 'GeneratePackageOnBuild=false'